In [34]:
import pandas as pd
import numpy as np

In [35]:
raw = pd.read_csv("/Users/holliswang/Desktop/sel_trial_data.csv", header=0)

In [41]:
US = {'LH': np.array([1,0,0]), 'M': np.array([0,1,0]), 'HL': np.array([0,0,1])}
CS = {'m': 0, 'p': 1}

In [190]:
a = sub_1['stimulus'].map(US)
a.size
# sub_1['test'] = np.array(list(a)).reshape(120, 3) # error
# np.reshape(np.array(list(1)), (120,3))

120

In [42]:
sub_1 = raw[raw['sub_id'] == 'LCP001'].iloc[:,[4,5,6]]

In [246]:
# sub_1['outcome'].replace(CS, inplace=True)
# sub_1['stimulus'].replace(US, inplace=True)
sub_1['stimulus_trans'] = sub_1['stimulus'].map(US)
sub_1['outcome_trans'] = sub_1['outcome'].map(CS)

In [250]:
sub_1['stimulus_trans'].values

array([array([1, 0, 0]), array([0, 1, 0]), array([0, 0, 1]),
       array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0]),
       array([1, 0, 0]), array([0, 1, 0]), array([0, 0, 1]),
       array([1, 0, 0]), array([1, 0, 0]), array([1, 0, 0]),
       array([0, 1, 0]), array([1, 0, 0]), array([1, 0, 0]),
       array([0, 0, 1]), array([0, 1, 0]), array([0, 1, 0]),
       array([0, 1, 0]), array([0, 0, 1]), array([0, 1, 0]),
       array([0, 1, 0]), array([0, 0, 1]), array([1, 0, 0]),
       array([0, 1, 0]), array([0, 0, 1]), array([0, 1, 0]),
       array([0, 0, 1]), array([0, 0, 1]), array([0, 1, 0]),
       array([0, 1, 0]), array([0, 0, 1]), array([0, 1, 0]),
       array([0, 1, 0]), array([0, 1, 0]), array([0, 0, 1]),
       array([0, 1, 0]), array([0, 1, 0]), array([1, 0, 0]),
       array([0, 1, 0]), array([0, 0, 1]), array([0, 0, 1]),
       array([1, 0, 0]), array([0, 1, 0]), array([0, 1, 0]),
       array([0, 1, 0]), array([0, 1, 0]), array([0, 0, 1]),
       array([0, 1, 0]),

In [193]:
stimulus.size

120

In [173]:
print(sub_1.head(5))
print(sub_1['stimulus_trans'].shape)

  stimulus outcome  resp_rating_cont stimulus_trans  outcome_trans
0       LH       m             21.20      [1, 0, 0]              0
1        M       p             49.36      [0, 1, 0]              1
2       HL       p             50.00      [0, 0, 1]              1
3       LH       m             19.92      [1, 0, 0]              0
4        M       p             75.60      [0, 1, 0]              1
(120,)


In [131]:
def softmax(x, beta):
    return np.exp(x * beta) / np.sum(np.exp(x * beta), axis=0)

In [243]:
outcome = sub_1['outcome_trans'] # reward/US
stimulus = sub_1['stimulus_trans'] # stimulus/CS

q = np.zeros((stimulus.size, stimulus[0].size)) #
alpha = 0.5
beta = 0.5

def calculate_weight(q, alpha, outcome, stimulus):
    for i in range(1,q.shape[0]):
        q[i] = q[i-1] + alpha * (outcome[i-1] * stimulus[i-1] - q[i-1])
    return q
    
q_t = calculate_weight(q, alpha, outcome, stimulus)
q_pdf = np.apply_along_axis(softmax, 1, q_t, beta) # transformed weights into density by softmax
q_ll = -np.log(q_pdf).sum(axis=0)

q_ll

array([135.85020934, 125.64698458, 135.63120637])

In [240]:
b = np.random.randint(0,10, 4)
b[2].size

1

In [233]:
import time
test = np.random.normal(0,1,(10000,1000))

In [235]:
def foo(x):
    return x**2

foo_v = np.vectorize(foo)
# print(foo_v(test)[0])
%timeit foo_v(test)

3 s ± 43.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [236]:
# print(np.apply_along_axis(foo, 1, test)[0])
%timeit np.apply_along_axis(foo, 1, test)

71.9 ms ± 2.12 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
